//
// Created by chenjs on 19-6-29.
//

#ifndef IMAGEPROCESSOR6_CONFIG_H
#define IMAGEPROCESSOR6_CONFIG_H

#define TESSERACT_PATH ("tesseract")
#define USE_CLI_TRANSLATOR (false)
//BUILT-IN TRANSLATOR IS AVAILABLE ONLY ON SINGLE LINE

#endif //IMAGEPROCESSOR6_CONFIG_H
